### PR TITLE
update php requirement to php5.5

### PR DESCRIPTION
**Pull request by macjohnny**
due to usage of ::class keyword

### CODE REVIEW

**Comment by macjohnny** [comment]
@martin-helmich can you merge this?

**Comment by macjohnny** [comment]
@martin-helmich how about merging this?

**Comment by martin-helmich** [comment]
@pstranghoener, what PHP version do we intend to support? PHP 5.4 is EOL, but some of the TYPO3 versions that typo3_forum supports (6.2) might still run on PHP 5.4.

**Comment by pstranghoener** [comment]
We backported that month ago, so we want to support PHP 5.4 as long as TYPO3 6.2 is in support.

**Comment by macjohnny** [comment]
but it is not php 5.4 compatible due to the usage of ::class
and so this must be changed in the ext_emconf.php
or you replace all the ::class statements.

**Comment by martin-helmich** [comment]
Reopened; @macjohnny is right, we should either 

1. raise the required PHP version to 5.5, *or*
2. remove the `::class` statements

The latter should be doable, there are not that many occurrences:

```
$ git grep '::class' | cat     
Classes/ViewHelpers/IfInstanceOfViewHelper.php:        $this->registerArgument('object', AbstractDomainObject::class, 'Object to check', true);
Classes/ViewHelpers/User/IfSubscribedViewHelper.php:        $this->registerArgument('object', SubscribeableInterface::class, 'Object to check', true);
Classes/ViewHelpers/User/IfSubscribedViewHelper.php:        $this->registerArgument('user', FrontendUser::class, 'className which object has to be', false, null);
Resources/Private/Libraries/GeSHi/geshi/oorexx.php:            '::attribute', '::class', '::constant', '::method',
```

**Comment by pstranghoener** [comment]
We will remove the ::class statements so thats why i closed it...

**Pull request closed without merging**
